---
SW1:
  hostname: '172.16.100.212'
  port: 22
  platform: 'cisco_ios'
  groups:
    - 'cisco_ios'

VMX_version17:
  hostname: '172.16.100.217'
  port: 22
  platform: 'junos'
  groups:
    - 'juniper'

VMX_version14:
  hostname: '172.16.100.245'
  port: 22
  platform: 'junos'
  groups:
    - 'juniper'

vSRX:
  hostname: '172.16.100.21'
  port: 22
  platform: 'junos'
  groups:
    - 'juniper'